### PR TITLE
Enforce maximum SD-NAME length of 32, per RFC5424

### PR DESCRIPTION
**Pull request by djaglowski**
Longer SD-NAMEs were previously allowed in fork of go-syslog
dependency, but it is not clear that this is necessary.

### CODE REVIEW

**Comment by djaglowski** [comment]
@pmm-sumo, @dmitryax, any opinions on this?

My thinking is that unless we have a clear and urgent need to make this specific exception to syslog format, we should use the upstream library.

**Comment by pmm-sumo** [comment]
THe robustness principle says it's good to "be conservative in what you do and liberal in what you accept from" and I find it's always a good rule to follow in IT :) 

I think it would be better to support SD-NAME's that are beyond the RFC but then don't think following the standard strictly is going to do much harm. @sumo-drosiek any more thoughts on that?

**Review by pmm-sumo — APPROVED** [review]

**Comment by dmitryax** [comment]
I don't know how popular this format is. If we remove its support, will we just drop the messages or they will be trimmed?

**Comment by sumo-drosiek** [comment]
> I don't know how popular this format is. If we remove its support, will we just drop the messages or they will be trimmed?

I would leave test for `RFC5424LongSDName`, just update it according to the change

**Review by dmitryax — APPROVED** [review]
Looks good to me assuming that `RFC5424LongSDName` is widely used.

**Review by jsirianni — APPROVED** [review]

**Pull request merged**
