### PR TITLE
Syslog input as wrapper

### PR DESCRIPTION
**Pull request by djaglowski**
The syslog_input operator was previously implemented
as a builder that built two operators. While this is
a perfectly fine solution, it happens to be the only
place in this codebase where multiple operators are
returned from a builder, excepting plugins.

This new implementation builds the same two operators,
but then wraps them together within a single operator.
This will allow for the eventual simplification of
other code, once plugins are also removed from this
codebase.

Related to #375, #380

### CODE REVIEW

**Comment by djaglowski** [comment]
The contrib failure is expected due to this change. I've proven out a change to `syslogreceiver.DecodeInputConfig` that will fix it:

```go
// DecodeInputConfig unmarshals the input operator
func (f ReceiverType) DecodeInputConfig(cfg config.Receiver) (*operator.Config, error) {
	logConfig := cfg.(*SysLogConfig)
	yamlBytes, _ := yaml.Marshal(logConfig.Input)
	inputCfg := syslog.NewSyslogInputConfig("syslog_input")
	inputCfg.SyslogBaseConfig = syslogparser.NewSyslogParserConfig("syslog_parser").SyslogBaseConfig

	if err := yaml.Unmarshal(yamlBytes, &inputCfg); err != nil {
		return nil, err
	}
	return &operator.Config{Builder: inputCfg}, nil
}
```

**Comment by djaglowski** [comment]
This change ended up simplifying the `syslog_input` operator in some notable ways. Particularly, I like that it removed the need for a custom unmarshal function.

**Comment by jsirianni** [comment]
@djaglowski do we expect contrib-tests to fail?

**Comment by djaglowski** [comment]
> @djaglowski do we expect contrib-tests to fail?

Yeah, see comment above.

**Review by jsirianni — APPROVED** [review]
I built this against my local contrib and tested TCP and UDP against rfc5424, looks good.

**Pull request merged**
