### PR TITLE
Change default value of 'parse_to' to 'attributes'

### PR DESCRIPTION
**Pull request by djaglowski**
Addresses one of two changes proposed in #431

### CODE REVIEW

**Comment by djaglowski** [comment]
Contrib test failure is due to a test that expects parsing results to be present in Body rather than Attributes.

**Review by jsirianni — APPROVED** [review]

**Comment by djaglowski** [comment]
@dmitryax, @tigrannajaryan, do you want to review this? It is a breaking change and currently only @pmm-sumo has written support on the proposal (#431). I think I recall hearing verbal agreement in last week's SIG, but want to make sure this is expected.

**Comment by tigrannajaryan** [comment]
@djaglowski I will take a look, sorry for the delay.

**Review by tigrannajaryan — APPROVED** [review]
I am fine with https://github.com/open-telemetry/opentelemetry-log-collection/issues/431 so approving based on the description that this moves us in that direction. 
I don't know this codebase well to actually review the code, I trust the other reviewers who know the codebase much better.

**Pull request merged**
