### PR TITLE
Remove '$' from field syntax

### PR DESCRIPTION
**Pull request by djaglowski**
This is a possible resolution to #164. This would be a major breaking change, so if accepted, the timing of a merge should be considered carefully.

---

This library has a construct called 'field', which has the
purpose of providing a concise way to refer to values in a
log record. The special symbol `$` has been used in key
words that refer to top level fields in the log record.
i.e. `$body`, `$attributes`, `$resource`

Additionally, some shorthand notion was supported. Notably,
`$.foo` and `.foo` were equivalent to `$body.foo`.

This change proposes to remove the usage of `$` in field syntax.
The main idea here is that all usages of field syntax MUST
begin with a key word i.e. `body`, `attributes`, `resource`.
With this requirement built in, there is no need to differentiate
between top level fields and arbitrary keys. The distinction is
implicit because the first word is always a top level field and
the remainder are arbitrary nested keys.

### CODE REVIEW

**Comment by djaglowski** [comment]
@jsirianni, @pmm-sumo, @rockb1017, please take a look. Any reservations on this approach?

**Comment by tigrannajaryan** [comment]
@dmitryax please have a look. Will our helm chart be affected by this change?

**Comment by tigrannajaryan** [comment]
The change looks good to me. The syntax becomes clearer.

I do not see any downsides to this change, are there any?

**Review by pmm-sumo — APPROVED** [review]

**Review by pmalek-sumo — COMMENTED** [review]
I like the idea of making it more explicit and easier to reason about.

🚀 some nits in `.md` tables

**Comment by dmitryax** [comment]
> @dmitryax please have a look. Will our helm chart be affected by this change?

It will be affected, but we can adopt for this change.

I like the proposal. The syntax seems cleaner now

**Review by dmitryax — APPROVED** [review]

**Review by rockb1017 — APPROVED** [review]

**Review by dmitryax — COMMENTED** [review]
LGTM, but should we throw deprecation log warnings?

**Comment by djaglowski** [comment]
> LGTM, but shouldn't we throw deprecation warnings in logs?

Unfortunately, there's not a great way to complain about the deprecated usage because it is processed during unmarshaling, where we don't have a handle to a logger. We could add a flag to the `Field` struct, set it during unmarshaling, and then log every time the field is used in the pipeline, but this seems overkill to me. In my opinion, logging about deprecations is a nice-to-have feature and probably not worth any substantial code changes to do it. If you feel strongly though, I can make the above change, or perhaps you see a better way that I missed. 

Another option is to fully remove support, but to detect the old syntax and return a clear error. This forces migration immediately, but at least would not be ambiguous at all.

**Comment by dmitryax** [comment]
Maybe we can drop the old interface support here but do all the necessary translation from the deprecated format in the collector-contrib? There we can throw all the warning during translation.

**Comment by djaglowski** [comment]
Unfortunately, I don't think unmarshaling in collector-contrib gives us a better opportunity to do this.

**Comment by djaglowski** [comment]
@dmitryax, can you clarify whether you see the lack of deprecation warning as a blocker? 

I do not see a good way to log warnings here or at the collector level, so I would prefer to either error or quietly support the old syntax.

**Comment by dmitryax** [comment]
What if we return an error of a `DeprecationError` type from unmarshal functions? Then contrib can look for that error and throw a warning message to the output with everything else working as usual.

**Comment by djaglowski** [comment]
> What if we return an error of a `DeprecationError` type from unmarshal functions? Then contrib can look for that error and throw a warning message to the output with everything else working as usual.

I liked this idea and gave it a shot, but unfortunately, the `yaml` library does not appear to allow for partial failures like this. Any error returned ultimately triggers a call to [fail](https://github.com/go-yaml/yaml/blob/7649d4548cb53a614db133b2a8ac1f31859dda8c/yaml.go#L259).

**Comment by dmitryax** [comment]
I see, if it's not possible to show a warning, I don't think silently support both versions is useful. Changing the interface right away seems to be a better option then.

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
